### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Djblaik** [LukeOnuke/AdminTools#12]
# **Description**
The bottom of the frame is cut off as shown in attached screenshots.
Also happens when window is maximised
# **Reproducing**
happens whenever I switch between tabs 
# **Log file**
[log-01-05-2022-@10-05-17.log](https://github.com/LukeOnuke/AdminTools/files/8598082/log-01-05-2022-%4010-05-17.log)
![image](https://user-images.githubusercontent.com/20061763/166127266-a4ccb738-b10c-4e79-8f96-c9e256132324.png)
![image](https://user-images.githubusercontent.com/20061763/166127299-1a4a4c21-e1b3-4e97-b554-a720fd03aa63.png)

**Comment by LukeOnuke** [comment]
Hm sounds like a missed anchor, will see what i can do to fix it

**Comment by LukeOnuke** [comment]
I think its fixed (?)
