### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Pequla** [LukeOnuke/AdminTools#3]
Request to add these features:

- One click server maintenance mode (https://github.com/Beocraft/ServerMaintenance)
- One much more detailed status (https://api.mcsrvstat.us/)
- Allow for multiple saved connections (ex. MySQL Workbench style)
![image](https://user-images.githubusercontent.com/58506649/95322375-b0427d80-089c-11eb-9e61-7064a1da2962.png)

- When connection is not available, detect it faster
- Use **JSON**, **YAML** or **XML** for storing login data
- Remove credential encryption (useless since RCON is unsecure)
- Change icons to Fonts Awesome (https://fontawesome.com/)
- Use **Materialze** as CSS framework (https://materializecss.com/)
- Remove Minecraft API status bar (It is static for last 5 years, pointless indeed)

**Comment by LukeOnuke** [comment]
Added in version 5
