### ISSUE TITLE
Version 5.0 BUGS

### ISSUE THREAD

**Issue by Pequla** [LukeOnuke/AdminTools#6]
Issues I found:
- New connection wizard stays on top of all the apps
- You can open multiple wizards and interact with the main windows GUI while the wizard is open
- When you press OK on the "stop the server" popup the app closes, instead make it go back to Connections tab
- Remove the spaces in the consoles date display (make it look like this [11:48:31], current one is [ 11:48:31 ])
- Move the settings to json too

**Comment by LukeOnuke** [comment]
Fixed in 5.1.0
